//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsType
    {
        public NewsType()
        {
            this.News = new HashSet<News>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
    
        public virtual ICollection<News> News { get; set; }
    }
}
