//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.Picture = new HashSet<Picture>();
            this.Comment = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Text { get; set; }
        public System.DateTime YayimTarihi { get; set; }
        public byte[] ResimYol { get; set; }
        public int CategoryId { get; set; }
        public int AuthorId { get; set; }
        public int NewsTypeId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Author Author { get; set; }
        public virtual NewsType NewsType { get; set; }
        public virtual ICollection<Picture> Picture { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
